import type { Metadata } from "next";
import "./globals.css";
import { PinProvider } from "./pin-context";
import GoogleMapsApiProvider from "./api-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <GoogleMapsApiProvider>
          <PinProvider>
            {children}
          </PinProvider>
        </GoogleMapsApiProvider>
      </body>
    </html>
  );
}
